### ISSUE TITLE
Beautify HTML when expanding html abbreviation

### ISSUE THREAD

**Issue by Defman21** [Defman21/Xemmet#2]
### Short summary

It works in Emmet, but doesn't work in Kemmet.

It:
- must beautify the expanded abbreviation
- should use special library for it

**Comment by Defman21** [comment]
@naatan @cgchoffman sorry for this notifying you there, but do you guys know how I can access `Format - Document Using... - HTML5 Fragment` from an add-on? I don't want to use external library for making all the indentation and beautifying, and there's already a built-in beautifier/formatter, so..

**Comment by th3coop** [comment]
I've not used the formatter backend before but I believe you'll want to use `ko.formatters.formatViewUsingConfigName`. 

Here's the signature of the function

```
 /**
     * Format the given view (defaults to the currentView when not supplied)
     * with the formatter configuration that has the supplied config name.
     * If there is a selection in this view then the formatter will work upon
     * the view's selection, else the formatter works on the complete document.
     * The targetted text will be replaced if the formatting is successful.

     * @param view {Components.interfaces.koIScintillaView}
     *        The view to format. Defaults to the current view if null.
     * @param {string} configName
     *        The name of the formatter configuration to use for formatting.
     */
    this.formatViewUsingConfigName = function formatViewUsingConfigName(view, configName)
```

So you'll have to get the emmet snippet, put it into a view, format it, then inject it into your new view... I feel like that could be made easier.  I smell a new SDK module.

Sorry I haven't tested this though @Defman21.  I'm not 100 sure on the above paragraph being the best way to do this.   I'm pretty sure you know how to get your hands on the source of that function if need be.  It's in the Komodo.jar in your install.

**Comment by Defman21** [comment]
@cgchoffman seems like formatters are available only in IDE. If that's true, then it's not a good solution for the issue. Xemmet should work in Edit as well.

**Comment by Defman21** [comment]
This looks good for me: https://github.com/beautify-web/js-beautify

Gonna use it.

**Comment by th3coop** [comment]
> then it's not a good solution for the issue

Agreed, good decision. Nice work on the alternative solution.
