### ISSUE TITLE
Something is wrong

### ISSUE THREAD

**Issue by harpreetsb** [Defman21/Xemmet#22]
### Short summary
not really sure how to explain
see video

https://youtu.be/npnZcvPb8kg

### Information

_Xemmet version:_  0.7.7

_OS:_ ubuntu 16.04

_Komodo version:_ 10.0.1

**Comment by Defman21** [comment]
I'll look into that, thanks.

**Comment by Defman21** [comment]
Could you share your log file?

**Comment by Defman21** [comment]
Nvm, reproduced.

**Comment by Defman21** [comment]
This is a Komodo bug.

**Comment by Defman21** [comment]
https://github.com/Defman21/Xemmet/commit/ff56baa0d2f29a22eb6f4dd444c8ef739993395f

**Comment by Defman21** [comment]
@harpreetsb https://github.com/Defman21/Xemmet/releases/tag/0.8.0-alpha

**Comment by harpreetsb** [comment]
## Thank you so much.
