### ISSUE TITLE
CTRL+TAB conflicts with a default Komodo keybinding

### ISSUE THREAD

**Issue by harpreetsb** [Defman21/Xemmet#23]
### Short summary
currently pressing `CTRL + TAB` makes current deleted text from current line, when no selection is made.
Rather it should fallback to default editor behavior to switch to last used tab.  

### Information

_Xemmet version:_ 0.80

_OS:_ Ubuntu 16.04

_Komodo version:_ 10.0.1

**Comment by Defman21** [comment]
It just uses the whole line for wrapping.

**Comment by harpreetsb** [comment]
possible to update this keybind.
I use CTRL+TAB for switching tabs. This feature makes hinders that.

**Comment by Defman21** [comment]
https://github.com/Defman21/Xemmet/commit/fdfd8ae208e450218719ffc831422b38b1a28e25

**Comment by Defman21** [comment]
https://github.com/Defman21/Xemmet/releases/tag/0.8.0-alpha.1

Now there's an option to disable wrap line when there's no selection.
