### ISSUE TITLE
Wrap selection in Komodo X

### ISSUE THREAD

**Issue by MaxAlekseyev** [Defman21/Xemmet#24]
### Information

_Xemmet version:_ 

_OS:_ 

_Komodo version:_

**Comment by MaxAlekseyev** [comment]
There was the conflict of local Keybinding with Ctrl+Tab that was assigned to "Next File (Tab)".
Works Ok now it Wrap selection denied.

Can I assing the wrap selection to some other keyboard shortcut?

**Comment by Defman21** [comment]
> Works Ok now it Wrap selection denied.

I don't understand this.

> Can I assing the wrap selection to some other keyboard shortcut?

Nope.
