### ISSUE TITLE
Wrap with abbreviation feature

### ISSUE THREAD

**Issue by Defman21** [Defman21/Xemmet#5]
### Short summary

It:
- must wrap selections only
- should use `ko/dialogs`
- should auto-indent the selection
- should fail gracefully if the abbreviation is bad
- should HTML-beautify itself (^ may be done with this item)

**Comment by Defman21** [comment]
A keybinding for it should be Shift+Tab or Ctrl+Tab.

**Comment by iakhator** [comment]
I will try it out, because emmet is not supported in 9.1

**Comment by Defman21** [comment]
Emmet is supported. Xemmet is not.

**Comment by Defman21** [comment]
https://github.com/Defman21/komodo-emmet this one should work as well as the one in the Packages, but mine is not giving any warnings when installing.
