### ISSUE TITLE
Better localization

### ISSUE THREAD

**Issue by Defman21** [Defman21/Xemmet#6]

**Comment by Defman21** [comment]
- "Xemmet works only in HTML & CSS" - means that Xemmet should work in pre-defined HTML & CSS languages and user-defined languages where HTML/CSS languages should work
- "Wrap Selection works only in HTML" - means that Xemmet Wrap Selection should work only in HTML + user-defined languages where HTML actions should work
- "Languages where Xemmet CSS actions should work" - means in which languages Xemmet CSS actions and abbreviations should be available (+ default)
- "Languages where Xemmet HTML actions should work" - means in which languages Xemmet HTML actions and abbreviations should be available (+ default)
- "Update languages" - means that Xemmet should update its languages list where it should work

**Comment by Naatan** [comment]
- Xemmet only works for HTML and CSS based languages
- Wrap selection only works for HTML based languages
- Additional CSS Language Names that Xemmet should run on
- Additional HTML Language Names that Xemmet should run on

**Comment by Defman21** [comment]
Thanks a lot!
