### ISSUE TITLE
Doesn't insert properly

### ISSUE THREAD

**Issue by Naatan** [Defman21/Xemmet#7]
### Short summary

Input:

```
div>h1{Hello}
```

Expected Output:

```
<div>
    <h1>Hello</h1>
</div>
```

Actual Output:

```
<div>
    <h1>Hello</h1></div>
```

**Comment by Defman21** [comment]
Thanks for finding this one!

**Comment by Defman21** [comment]
This is a bug in [the lib I'm using](http://jsbeautifier.org/)

**Comment by Naatan** [comment]
Well is it tracked? You might want to report it to them.

**Comment by Defman21** [comment]
Gonna do.

**Comment by Defman21** [comment]
https://github.com/beautify-web/js-beautify/issues/948

**Comment by Defman21** [comment]
I'm wondering about using Komodo's HTML beautifier if it's available (so the user uses IDE version) and fallback on js-beautify. Or maybe I should use a different library.

**Comment by Naatan** [comment]
That would be a good compromise. I would value consistency as a user.

**Comment by Defman21** [comment]
Well, it would be too hard to implement because formatters works only with views but the beautify code is generating in Xemmet. I don't want to beautify the whole file or create a fake scintilla view, so I've just fixed the original beautify-js behavior.
